from .news import do_news
from .youtube import do_youtube
from .movie import do_movie
from .wallpaper import do_wallpaper
from .quote import do_quote
from .crypto import do_crypto
from  .fb_login import login
from  .instagram import do_insta
from  .wiki import wikipedia